import { createDeliverycityModel } from '../../src/models/deliverycity.model';
import { createExpenseModel } from '../../src/models/expense.model';
import { createFaqModel } from '../../src/models/faq.model';
import { createFaqanswerModel } from '../../src/models/faqanswer.model';
import { createItemModel } from '../../src/models/item.model';
import { createItemDecoyModel } from '../../src/models/itemdecoy.model';
import { createItemOfferModel } from '../../src/models/itemoffer.model';
import { createOrderModel } from '../../src/models/order.model';
import { createPaymentModel } from '../../src/models/payment.model';
import { createDeliveryNoteModel } from '../../src/models/printables/deliverynote.model';
import { createInvoiceModel } from '../../src/models/printables/invoice.model';
import { createJobCardModel } from '../../src/models/printables/jobcard.model';
import { createPaymentRelatedModel } from '../../src/models/printables/paymentrelated/paymentrelated.model';
import { createPickupLocationModel } from '../../src/models/printables/pickuplocation.model';
import { createReceiptModel } from '../../src/models/printables/receipt.model';
import { createInvoiceRelatedModel } from '../../src/models/printables/related/invoicerelated.model';
import { createExpenseReportModel } from '../../src/models/printables/report/expenesreport.model';
import { createInvoicesReportModel } from '../../src/models/printables/report/invoicereport.model';
import { createProfitandlossReportModel } from '../../src/models/printables/report/profitandlossreport.model';
import { createSalesReportModel } from '../../src/models/printables/report/salesreport.model';
import { createTaxReportModel } from '../../src/models/printables/report/taxreport.model';
import { createInvoiceSettingModel } from '../../src/models/printables/settings/invoicesettings.model';
import { createPromocodeModel } from '../../src/models/promocode.model';
import { createReviewModel } from '../../src/models/review.model';
import { createCustomerModel } from '../../src/models/user-related/customer.model';
import { createStaffModel } from '../../src/models/user-related/staff.model';
import { connectStockCounterDatabase } from '../../src/stock-counter-local';
import { vi, describe, it, expect } from 'vitest';

vi.mock('../../src/models/printables/paymentrelated/paymentrelated.model');
vi.mock('../../src/models/printables/related/invoicerelated.model');
vi.mock('../../src/models/printables/report/expenesreport.model');
vi.mock('../../src/models/printables/report/invoicereport.model');
vi.mock('../../src/models/printables/report/profitandlossreport.model');
vi.mock('../../src/models/printables/report/salesreport.model');
vi.mock('../../src/models/printables/report/taxreport.model');
vi.mock('../../src/models/printables/settings/invoicesettings.model');
vi.mock('../../src/models/printables/deliverynote.model');
// vi.mock('../../src/models/estimate.model');
vi.mock('../../src/models/printables/invoice.model');
vi.mock('../../src/models/printables/jobcard.model');
vi.mock('../../src/models/printables/pickuplocation.model');
vi.mock('../../src/models/printables/receipt.model');
vi.mock('../../src/models/user-related/customer.model');
vi.mock('../../src/models/user-related/staff.model');
vi.mock('../../src/models/deliverycity.model');
vi.mock('../../src/models/expense.model');
vi.mock('../../src/models/faq.model');
vi.mock('../../src/models/faqanswer.model');
vi.mock('../../src/models/item.model');
vi.mock('../../src/models/itemdecoy.model');
vi.mock('../../src/models/itemoffer.model');
vi.mock('../../src/models/order.model');
vi.mock('../../src/models/payment.model');
vi.mock('../../src/models/promocode.model');
vi.mock('../../src/models/review.model');
vi.mock('../../src/models/item-limited.model');

describe('connectStockCounterDatabase', () => {
  const databaseUrl = 'mongodb://localhost:27017/node_testyyyyy';

  it('should create all models', async() => {
    await connectStockCounterDatabase(databaseUrl);
    expect(createPaymentRelatedModel).toHaveBeenCalledWith(databaseUrl);
    expect(createInvoiceRelatedModel).toHaveBeenCalledWith(databaseUrl);
    expect(createExpenseReportModel).toHaveBeenCalledWith(databaseUrl);
    expect(createInvoicesReportModel).toHaveBeenCalledWith(databaseUrl);
    expect(createProfitandlossReportModel).toHaveBeenCalledWith(databaseUrl);
    expect(createSalesReportModel).toHaveBeenCalledWith(databaseUrl);
    expect(createTaxReportModel).toHaveBeenCalledWith(databaseUrl);
    expect(createInvoiceSettingModel).toHaveBeenCalledWith(databaseUrl);
    expect(createDeliveryNoteModel).toHaveBeenCalledWith(databaseUrl);
    expect(createInvoiceModel).toHaveBeenCalledWith(databaseUrl);
    expect(createJobCardModel).toHaveBeenCalledWith(databaseUrl);
    expect(createPickupLocationModel).toHaveBeenCalledWith(databaseUrl);
    expect(createReceiptModel).toHaveBeenCalledWith(databaseUrl);
    expect(createCustomerModel).toHaveBeenCalledWith(databaseUrl);
    expect(createStaffModel).toHaveBeenCalledWith(databaseUrl);
    expect(createDeliverycityModel).toHaveBeenCalledWith(databaseUrl);
    expect(createExpenseModel).toHaveBeenCalledWith(databaseUrl);
    expect(createFaqModel).toHaveBeenCalledWith(databaseUrl);
    expect(createFaqanswerModel).toHaveBeenCalledWith(databaseUrl);
    expect(createItemModel).toHaveBeenCalledWith(databaseUrl);
    expect(createItemDecoyModel).toHaveBeenCalledWith(databaseUrl);
    expect(createItemOfferModel).toHaveBeenCalledWith(databaseUrl);
    expect(createOrderModel).toHaveBeenCalledWith(databaseUrl);
    expect(createPaymentModel).toHaveBeenCalledWith(databaseUrl);
    expect(createPromocodeModel).toHaveBeenCalledWith(databaseUrl);
    expect(createReviewModel).toHaveBeenCalledWith(databaseUrl);
  });
});
